import next from '@parshlo/config/eslint/next';

export default [
  ...next,
  {
    files: ['**/next-env.d.ts'],
    rules: {
      // Auto-generated by Next.js; triple-slash refs are required for route types.
      '@typescript-eslint/triple-slash-reference': 'off',
    },
  },
  {
    rules: {
      // Next.js Link components handle internal routing; allow plain <a> for
      // external links without forcing next/link migrations.
      '@next/next/no-html-link-for-pages': 'off',
    },
  },
];
