import { createHash } from 'node:crypto';

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

interface InvoiceItem {
  productName: string;
  quantity: number;
  unitPricePaise: number;
  gstRate: string;
  lineSubtotalPaise: number;
  lineGstPaise: number;
  lineTotalPaise: number;
}

export interface InvoiceData {
  orderNumber: string;
  invoiceNumber: string;
  placedAt: Date;
  seller: {
    name: string;
    gstin: string;
    addressLines: string[];
    state: string;
  };
  buyer: {
    businessName: string;
    gstin: string;
    addressLines: string[];
    state: string;
  };
  items: InvoiceItem[];
  subtotalPaise: number;
  gstPaise: number;
  totalPaise: number;
}

function formatIstDate(date: Date): string {
  const parts = new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Asia/Kolkata',
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  }).formatToParts(date);
  const v = (type: Intl.DateTimeFormatPartTypes): string =>
    parts.find((part) => part.type === type)?.value ?? '';

  return `${v('day')}-${v('month')}-${v('year')}`;
}

/**
 * Render a GST-compliant tax invoice PDF. Returns both the bytes and a
 * SHA-256 digest of the bytes for retention/audit hashing.
 *
 * The format is intentionally minimal — single column, mono-priced — so it's
 * Outlook-safe and easy to verify against state GST portal data.
 */
export async function renderInvoicePdf(
  data: InvoiceData,
): Promise<{ bytes: Uint8Array; sha256: string }> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]); // A4
  const helv = await doc.embedFont(StandardFonts.Helvetica);
  const helvBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const mono = await doc.embedFont(StandardFonts.Courier);

  const black = rgb(0.05, 0.07, 0.09);
  const grey = rgb(0.42, 0.45, 0.5);
  const accent = rgb(0.05, 0.28, 0.2);

  const margin = 40;
  let y = 800;
  const draw = (
    text: string,
    opts: { x?: number; size?: number; font?: typeof helv; color?: typeof black } = {},
  ) => {
    page.drawText(text, {
      x: opts.x ?? margin,
      y,
      size: opts.size ?? 10,
      font: opts.font ?? helv,
      color: opts.color ?? black,
    });
  };

  // ---- Header ----
  draw('TAX INVOICE', { size: 18, font: helvBold, color: accent });
  y -= 22;
  draw(`Invoice #: ${data.invoiceNumber}`, { size: 9, color: grey });
  y -= 12;
  draw(`Order #: ${data.orderNumber}`, { size: 9, color: grey });
  y -= 12;
  draw(`Date: ${formatIstDate(data.placedAt)}`, { size: 9, color: grey });

  // ---- Seller / Buyer block ----
  y -= 30;
  const colMid = 297.64;
  drawBlock(page, helv, helvBold, margin, y, 'SELLER', data.seller, black, grey);
  drawBlock(page, helv, helvBold, colMid, y, 'BUYER (BILL TO)', data.buyer, black, grey);
  y -= 110;

  // ---- Items table ----
  page.drawRectangle({
    x: margin,
    y: y - 16,
    width: 555.28 - margin,
    height: 18,
    color: rgb(0.94, 0.96, 0.95),
  });
  draw('PRODUCT', { x: margin + 6, size: 9, font: helvBold });
  draw('QTY', { x: margin + 290, size: 9, font: helvBold });
  draw('UNIT', { x: margin + 330, size: 9, font: helvBold });
  draw('GST RATE', { x: margin + 400, size: 9, font: helvBold });
  draw('TOTAL', { x: margin + 460, size: 9, font: helvBold });
  y -= 22;

  for (const item of data.items) {
    page.drawText(item.productName.slice(0, 44), {
      x: margin + 6,
      y,
      size: 9,
      font: helv,
      color: black,
    });
    page.drawText(String(item.quantity), { x: margin + 290, y, size: 9, font: mono, color: black });
    page.drawText(rupees(item.unitPricePaise), {
      x: margin + 330,
      y,
      size: 9,
      font: mono,
      color: black,
    });
    page.drawText(`${item.gstRate}% incl.`, {
      x: margin + 400,
      y,
      size: 8,
      font: mono,
      color: grey,
    });
    page.drawText(rupees(item.lineTotalPaise), {
      x: margin + 460,
      y,
      size: 9,
      font: mono,
      color: black,
    });
    y -= 16;
  }

  // ---- Totals ----
  y -= 8;
  page.drawLine({
    start: { x: margin, y: y + 4 },
    end: { x: 555.28, y: y + 4 },
    color: grey,
    thickness: 0.5,
  });
  y -= 14;
  drawRight(page, 'Subtotal', rupees(data.subtotalPaise), margin, y, mono, helv);
  y -= 14;
  drawRight(page, 'GST Rate', '5% included', margin, y, mono, helv);
  y -= 16;
  drawRight(page, 'TOTAL (INR)', rupees(data.totalPaise), margin, y, mono, helvBold, true);

  // ---- Footer ----
  page.drawText('Generated by Parshlo Platform · This is a system-generated invoice.', {
    x: margin,
    y: 40,
    size: 8,
    font: helv,
    color: grey,
  });

  const bytes = await doc.save();
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  return { bytes, sha256 };
}

function drawBlock(
  page: ReturnType<PDFDocument['addPage']>,
  helv: Awaited<ReturnType<PDFDocument['embedFont']>>,
  helvBold: Awaited<ReturnType<PDFDocument['embedFont']>>,
  x: number,
  y: number,
  label: string,
  block: {
    name?: string;
    businessName?: string;
    gstin: string;
    addressLines: string[];
    state: string;
  },
  black: ReturnType<typeof rgb>,
  grey: ReturnType<typeof rgb>,
): void {
  page.drawText(label, { x, y, size: 8, font: helvBold, color: grey });
  page.drawText(block.name ?? block.businessName ?? '', {
    x,
    y: y - 14,
    size: 11,
    font: helvBold,
    color: black,
  });
  let cy = y - 28;
  for (const line of block.addressLines) {
    page.drawText(line, { x, y: cy, size: 9, font: helv, color: black });
    cy -= 11;
  }
  page.drawText(`State: ${block.state}`, { x, y: cy, size: 9, font: helv, color: grey });
  cy -= 11;
  page.drawText(`GSTIN: ${block.gstin}`, { x, y: cy, size: 9, font: helv, color: grey });
}

function drawRight(
  page: ReturnType<PDFDocument['addPage']>,
  label: string,
  value: string,
  margin: number,
  y: number,
  mono: Awaited<ReturnType<PDFDocument['embedFont']>>,
  helv: Awaited<ReturnType<PDFDocument['embedFont']>>,
  bold = false,
): void {
  page.drawText(label, { x: margin + 380, y, size: bold ? 11 : 10, font: bold ? helv : helv });
  page.drawText(value, { x: margin + 460, y, size: bold ? 11 : 10, font: mono });
}

function rupees(paise: number): string {
  return `Rs ${(paise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
}
