-- Add the seven catalog SKUs that were present in the product sheet but not in
-- the app database. This migration is intentionally non-destructive: it only
-- upserts these slugs and does not remove or disable any existing product rows.

INSERT INTO "ProductCategory" ("id", "slug", "name", "createdAt", "updatedAt")
VALUES
  ('seed-category-corticosteroid', 'corticosteroid', 'Corticosteroids', NOW(), NOW()),
  ('seed-category-nutraceuticals', 'nutraceuticals', 'Vitamins & Nutraceuticals', NOW(), NOW()),
  ('seed-category-protein-supplement', 'protein-supplement', 'Nutritional Powders', NOW(), NOW()),
  ('seed-category-analgesics', 'analgesics', 'Analgesics & NSAIDs', NOW(), NOW())
ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "Product" (
  "id",
  "slug",
  "name",
  "composition",
  "strength",
  "form",
  "packaging",
  "description",
  "manufacturer",
  "hsnCode",
  "categoryId",
  "imageKeys",
  "prescriptionRequired",
  "scheduleDrug",
  "wholesalePricePaise",
  "rateAPaise",
  "rateBPaise",
  "mrpPaise",
  "gstRate",
  "moq",
  "status",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'seed-product-defcya-12-mg-cap',
    'defcya-12-mg-cap',
    'Defcya 12 Mg Cap',
    'Composition pending stakeholder confirmation',
    '12mg',
    'CAPSULE'::"ProductForm",
    '10 capsules/strip · 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'corticosteroid'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    17349,
    17349,
    19276,
    25300,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-ironest-xt-tab',
    'ironest-xt-tab',
    'Ironest XT Tab',
    'Composition pending stakeholder confirmation',
    'XT',
    'TABLET'::"ProductForm",
    '10 tablets/strip · 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'nutraceuticals'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    14537,
    14537,
    16152,
    21200,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-metiace-tab',
    'metiace-tab',
    'Metiace Tab',
    'Composition pending stakeholder confirmation',
    'Pending',
    'TABLET'::"ProductForm",
    '10 tablets/strip · 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'nutraceuticals'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    7543,
    7543,
    8381,
    11000,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-protilo-kesar',
    'protilo-kesar',
    'Protilo 200 Gm Powder (Kesar)',
    'Composition pending stakeholder confirmation',
    '200g',
    'POWDER'::"ProductForm",
    '200g pack',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '21069099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'protein-supplement'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    26743,
    26743,
    29714,
    39000,
    'FIVE'::"GstRate",
    6,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-tremecya-tab',
    'tremecya-tab',
    'Tremecya Tab',
    'Composition pending stakeholder confirmation',
    'Pending',
    'TABLET'::"ProductForm",
    '10 tablets/strip · 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'analgesics'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    15429,
    15429,
    17143,
    22500,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-tremecya-d-tab',
    'tremecya-d-tab',
    'Tremecya D Tab',
    'Composition pending stakeholder confirmation',
    'Pending',
    'TABLET'::"ProductForm",
    '10 tablets/strip · 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'analgesics'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    9120,
    9120,
    10133,
    13300,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-upfolet-tab',
    'upfolet-tab',
    'Upfolet Tab',
    'Composition pending stakeholder confirmation',
    'Pending',
    'TABLET'::"ProductForm",
    '10 tablets/strip · 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'nutraceuticals'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    13851,
    13851,
    15390,
    20200,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  )
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "composition" = EXCLUDED."composition",
  "strength" = EXCLUDED."strength",
  "form" = EXCLUDED."form",
  "packaging" = EXCLUDED."packaging",
  "description" = EXCLUDED."description",
  "manufacturer" = EXCLUDED."manufacturer",
  "hsnCode" = EXCLUDED."hsnCode",
  "categoryId" = EXCLUDED."categoryId",
  "prescriptionRequired" = EXCLUDED."prescriptionRequired",
  "scheduleDrug" = EXCLUDED."scheduleDrug",
  "wholesalePricePaise" = EXCLUDED."wholesalePricePaise",
  "rateAPaise" = EXCLUDED."rateAPaise",
  "rateBPaise" = EXCLUDED."rateBPaise",
  "mrpPaise" = EXCLUDED."mrpPaise",
  "gstRate" = EXCLUDED."gstRate",
  "moq" = EXCLUDED."moq",
  "status" = EXCLUDED."status",
  "updatedAt" = NOW();
