-- Add the complete approved 39-SKU catalog as a safe baseline migration.
-- Product names and prices are copied from the Prashlo Catalog Price List.
-- This is intentionally non-destructive: it upserts products by slug, keeps
-- existing image keys, and does not run the dev seed that wipes data.
--
-- The current schema requires each Product to have a ProductCategory. We use one
-- internal "catalog" category for all products so no public category filters are
-- reintroduced.

INSERT INTO "ProductCategory" ("id", "slug", "name", "description", "createdAt", "updatedAt")
VALUES
  (
    'seed-category-catalog',
    'catalog',
    'Catalog',
    'Internal required product bucket; not intended as a storefront filter.',
    NOW(),
    NOW()
  )
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "updatedAt" = NOW();

INSERT INTO "Product" (
  "id",
  "slug",
  "name",
  "composition",
  "strength",
  "form",
  "packaging",
  "description",
  "manufacturer",
  "hsnCode",
  "categoryId",
  "imageKeys",
  "prescriptionRequired",
  "scheduleDrug",
  "wholesalePricePaise",
  "rateAPaise",
  "rateBPaise",
  "mrpPaise",
  "gstRate",
  "moq",
  "status",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'seed-product-calonest-plus-cap',
    'calonest-plus-cap',
    'CALONEST® - PLUS CAP',
    'Calcium Citrate 1000mg + Vitamin D3 + Vitamin K2-7 + Magnesium + Zinc',
    '1000mg combo',
    'CAPSULE'::"ProductForm",
    '10 capsules/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    16046,
    16046,
    17829,
    23400,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-calonest-xt-tab',
    'calonest-xt-tab',
    'CALONEST® - XT TAB',
    'Calcium Citrate Maleate 1000mg + Vitamin D3 + Magnesium + Zinc',
    '1000mg combo',
    'TABLET'::"ProductForm",
    '15 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    16046,
    16046,
    17829,
    23400,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-calonest-tab',
    'calonest-tab',
    'CALONEST® TAB',
    'Calcium Carbonate 500mg + Vitamin D3 250 IU',
    '500mg + 250 IU',
    'TABLET'::"ProductForm",
    '15 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    12549,
    12549,
    13943,
    18300,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-collamat-plus-tab',
    'collamat-plus-tab',
    'COLLAMAT® - PLUS TAB',
    'Undenatured Type II Collagen 40mg + Glucosamine Sulphate 750mg + MSM',
    '40mg + 750mg combo',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    37166,
    37166,
    41295,
    54200,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-cosamax-dn-tab',
    'cosamax-dn-tab',
    'COSAMAX - DN TAB',
    'Diacerein 50mg + Glucosamine Sulphate 750mg',
    '50mg + 750mg',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    15566,
    15566,
    17295,
    22700,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-cumigold-cap',
    'cumigold-cap',
    'CUMIGOLD CAP',
    'Curcumin (95% Curcuminoids) 500mg + Piperine 5mg',
    '500mg + 5mg',
    'CAPSULE'::"ProductForm",
    '10 capsules/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '21069099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    22354,
    22354,
    24838,
    32600,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-defcya-12-mg-cap',
    'defcya-12-mg-cap',
    'DEFCYA - 12 MG CAP',
    'Composition pending stakeholder confirmation',
    '12mg',
    'CAPSULE'::"ProductForm",
    '10 capsules/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    17349,
    17349,
    19276,
    25300,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-defcya-6-tab',
    'defcya-6-tab',
    'DEFCYA - 6 MG CAP',
    'Deflazacort 6mg',
    '6mg',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    10286,
    10286,
    11429,
    15000,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-dexlet-d-cap',
    'dexlet-d-cap',
    'DEXLET® - D CAP',
    'Doxylamine Succinate 10mg + Pyridoxine HCl (Vitamin B6) 10mg',
    '10mg + 10mg',
    'CAPSULE'::"ProductForm",
    '10 capsules/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    8091,
    8091,
    8990,
    11800,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-dexlet-tab',
    'dexlet-tab',
    'DEXLET® TAB',
    'Doxylamine Succinate 10mg',
    '10mg',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    6240,
    6240,
    6933,
    9100,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-dibenza-spray',
    'dibenza-spray',
    'DIBENZA SPRAY',
    'Diclofenac Diethylamine 1.16% + Methyl Salicylate + Menthol + Linseed Oil',
    '1.16% w/w',
    'OTHER'::"ProductForm",
    '50ml spray bottle',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    16046,
    16046,
    17829,
    23400,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-ezyrol-d3-60k-cap',
    'ezyrol-d3-60k-cap',
    'EZYROL - 60K CAP',
    'Cholecalciferol (Vitamin D3) 60,000 IU',
    '60,000 IU',
    'CAPSULE'::"ProductForm",
    '4 capsules/strip',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    8503,
    8503,
    9448,
    12400,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-ezyrol-nano-shots',
    'ezyrol-nano-shots',
    'EZYROL - NANO SHOTS',
    'Cholecalciferol (Vitamin D3) 60,000 IU - Nano Liquid',
    '60,000 IU / 5ml',
    'OTHER'::"ProductForm",
    '5ml shot - 4 shots/pack',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    4937,
    4937,
    5486,
    7200,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-fawound-ds-tab',
    'fawound-ds-tab',
    'FAWOUND® - DS TAB',
    'Trypsin-Chymotrypsin 100,000 AU (Double Strength)',
    '100,000 AU',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    27634,
    27634,
    30705,
    40300,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-fawound-plus-tab',
    'fawound-plus-tab',
    'FAWOUND® - PLUS TAB',
    'Trypsin-Chymotrypsin 50,000 AU + Diclofenac 50mg + Paracetamol 325mg',
    'Combo',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    19611,
    19611,
    21790,
    28600,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-fawound-tab',
    'fawound-tab',
    'FAWOUND® TAB',
    'Trypsin-Chymotrypsin 50,000 AU',
    '50,000 AU',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    13757,
    13757,
    15286,
    20063,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-femsure-tab',
    'femsure-tab',
    'FEMSURE® TAB',
    'Myo-Inositol 550mg + D-Chiro-Inositol 13.8mg + Folic Acid 200mcg + Vitamin D3 + Chromium',
    'Combo',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '21069099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    13577,
    13577,
    15086,
    19800,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-flexcel-60-tab',
    'flexcel-60-tab',
    'FLEXCEL - 60 TAB',
    'Etoricoxib 60mg',
    '60mg',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    5760,
    5760,
    6400,
    8400,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-flexcel-90-tab',
    'flexcel-90-tab',
    'FLEXCEL - 90 TAB',
    'Etoricoxib 90mg',
    '90mg',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    7200,
    7200,
    8000,
    10500,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-flexcel-eth-4-tab',
    'flexcel-eth-4-tab',
    'FLEXCEL - ETH 4 TAB',
    'Etodolac 400mg + Thiocolchicoside 4mg',
    '400mg + 4mg',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    17349,
    17349,
    19276,
    25300,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-fracsure-plus-tab',
    'fracsure-plus-tab',
    'FRACSURE - PLUS TAB',
    'Calcitriol 0.25mcg + Calcium Citrate Maleate 1000mg + Vitamin K2-7 + Magnesium + Zinc',
    '0.25mcg + 1000mg combo',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    15223,
    15223,
    16914,
    22200,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-fracsure-tab',
    'fracsure-tab',
    'FRACSURE TAB',
    'Calcitriol 0.25mcg + Calcium Carbonate 500mg + Zinc 7.5mg',
    '0.25mcg combo',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    28937,
    28937,
    32152,
    42200,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-gbcard-nt-tab',
    'gbcard-nt-tab',
    'GBCARD® - NT TAB',
    'Nebivolol 5mg + Telmisartan 40mg',
    '5mg + 40mg',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    16046,
    16046,
    17829,
    23400,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-ironest-tab',
    'ironest-tab',
    'IRONEST TAB',
    'Ferrous Ascorbate 100mg + Folic Acid 1.5mg',
    '100mg + 1.5mg',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    14537,
    14537,
    16152,
    21200,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-ironest-xt-tab',
    'ironest-xt-tab',
    'IRONEST -XT TAB',
    'Composition pending stakeholder confirmation',
    'XT',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    14537,
    14537,
    16152,
    21200,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-metiace-tab',
    'metiace-tab',
    'METIACE® TAB',
    'Composition pending stakeholder confirmation',
    'Pending',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    7543,
    7543,
    8381,
    11000,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-protilo-dm',
    'protilo-dm',
    'PROTILO® - DM 400 GM POWDER (CHOCOLATE)',
    'Whey + Soy Protein Isolate + Slow-release Carbs + Fibre + Vitamins/Minerals (no added sugar)',
    '200g protein/kg',
    'POWDER'::"ProductForm",
    '400g tin',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '21069099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    54240,
    54240,
    60267,
    79100,
    'FIVE'::"GstRate",
    6,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-protilo-sf',
    'protilo-sf',
    'PROTILO® - SF 200 GM POWDER (CHOCOLATE)',
    'Whey Protein Concentrate + Vitamins/Minerals (Sugar-Free, unflavoured)',
    '200g protein/kg',
    'POWDER'::"ProductForm",
    '500g tin',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '21069099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    28389,
    28389,
    31543,
    41400,
    'FIVE'::"GstRate",
    6,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-protilo-sf-chocolate',
    'protilo-sf-chocolate',
    'PROTILO® - SF 200 GM POWDER (CHOCOLATE)',
    'Whey Protein Concentrate + Vitamins/Minerals - Chocolate Flavour (Sugar-Free)',
    '200g protein/kg',
    'POWDER'::"ProductForm",
    '500g tin',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '21069099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    30857,
    30857,
    34286,
    45000,
    'FIVE'::"GstRate",
    6,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-protilo-sf-kesar',
    'protilo-sf-kesar',
    'PROTILO® - SF 200 GM POWDER (KESAR)',
    'Whey Protein Concentrate + Vitamins/Minerals - Kesar (Saffron) Flavour (Sugar-Free)',
    '200g protein/kg',
    'POWDER'::"ProductForm",
    '500g tin',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '21069099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    28433,
    28433,
    31592,
    41465,
    'FIVE'::"GstRate",
    6,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-protilo-chocolate',
    'protilo-chocolate',
    'PROTILO® 200 GM POWDER (CHOCOLATE)',
    'Whey Protein Concentrate + Vitamins/Minerals - Chocolate Flavour',
    '200g protein/kg',
    'POWDER'::"ProductForm",
    '500g tin',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '21069099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    26743,
    26743,
    29714,
    39000,
    'FIVE'::"GstRate",
    6,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-protilo-kesar',
    'protilo-kesar',
    'PROTILO® 200 GM POWDER (KESAR)',
    'Composition pending stakeholder confirmation',
    '200g',
    'POWDER'::"ProductForm",
    '200g pack',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '21069099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    26743,
    26743,
    29714,
    39000,
    'FIVE'::"GstRate",
    6,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-roxinoe-dt-tab',
    'roxinoe-dt-tab',
    'ROXINOE - DT',
    'Roxithromycin 50mg (Dispersible)',
    '50mg',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30041020',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    8983,
    8983,
    9981,
    13100,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-tendofab-plus-cap',
    'tendofab-plus-cap',
    'TENDOFAB® - PLUS CAP',
    'Methylsulfonylmethane (MSM) + Glucosamine Sulphate + Diacerein',
    'Combo',
    'CAPSULE'::"ProductForm",
    '10 capsules/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    26242,
    26242,
    29158,
    38270,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-tendofab-v-tab',
    'tendofab-v-tab',
    'TENDOFAB® - V TAB',
    'Methylsulfonylmethane (MSM) + Vitamin C + Undenatured Type II Collagen',
    'Combo',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    20709,
    20709,
    23010,
    30200,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-tremecya-tab',
    'tremecya-tab',
    'TREMECYA TAB',
    'Composition pending stakeholder confirmation',
    'Pending',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    15429,
    15429,
    17143,
    22500,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-tremecya-d-tab',
    'tremecya-d-tab',
    'TREMECYA - D TAB',
    'Composition pending stakeholder confirmation',
    'Pending',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    TRUE,
    'SCHEDULE_H'::"ScheduleDrug",
    9120,
    9120,
    10133,
    13300,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-upfolet-plus-tab',
    'upfolet-plus-tab',
    'UPFOLET® - PLUS TAB',
    'L-Methylfolate 1mg + Methylcobalamin (Vitamin B12) 1500mcg + Pyridoxal-5-Phosphate (Vitamin B6)',
    '1mg + 1500mcg combo',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    9600,
    9600,
    10667,
    14000,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  ),
  (
    'seed-product-upfolet-tab',
    'upfolet-tab',
    'UPFOLET® TAB',
    'Composition pending stakeholder confirmation',
    'Pending',
    'TABLET'::"ProductForm",
    '10 tablets/strip - 10 strips/box',
    'Product details pending stakeholder confirmation.',
    'Parshlo',
    '30049099',
    (SELECT "id" FROM "ProductCategory" WHERE "slug" = 'catalog'),
    ARRAY[]::TEXT[],
    FALSE,
    'NONE'::"ScheduleDrug",
    13851,
    13851,
    15390,
    20200,
    'FIVE'::"GstRate",
    10,
    'ACTIVE'::"ProductStatus",
    NOW(),
    NOW()
  )
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "composition" = EXCLUDED."composition",
  "strength" = EXCLUDED."strength",
  "form" = EXCLUDED."form",
  "packaging" = EXCLUDED."packaging",
  "description" = EXCLUDED."description",
  "manufacturer" = EXCLUDED."manufacturer",
  "hsnCode" = EXCLUDED."hsnCode",
  "categoryId" = EXCLUDED."categoryId",
  "prescriptionRequired" = EXCLUDED."prescriptionRequired",
  "scheduleDrug" = EXCLUDED."scheduleDrug",
  "wholesalePricePaise" = EXCLUDED."wholesalePricePaise",
  "rateAPaise" = EXCLUDED."rateAPaise",
  "rateBPaise" = EXCLUDED."rateBPaise",
  "mrpPaise" = EXCLUDED."mrpPaise",
  "gstRate" = EXCLUDED."gstRate",
  "moq" = EXCLUDED."moq",
  "status" = EXCLUDED."status",
  "deletedAt" = NULL,
  "updatedAt" = NOW();

INSERT INTO "Inventory" ("productId", "availableQty", "reservedQty", "reorderLevel", "updatedAt")
SELECT "id", 5000, 0, 200, NOW()
FROM "Product"
WHERE "slug" IN (
  'calonest-plus-cap',
  'calonest-xt-tab',
  'calonest-tab',
  'collamat-plus-tab',
  'cosamax-dn-tab',
  'cumigold-cap',
  'defcya-12-mg-cap',
  'defcya-6-tab',
  'dexlet-d-cap',
  'dexlet-tab',
  'dibenza-spray',
  'ezyrol-d3-60k-cap',
  'ezyrol-nano-shots',
  'fawound-ds-tab',
  'fawound-plus-tab',
  'fawound-tab',
  'femsure-tab',
  'flexcel-60-tab',
  'flexcel-90-tab',
  'flexcel-eth-4-tab',
  'fracsure-plus-tab',
  'fracsure-tab',
  'gbcard-nt-tab',
  'ironest-tab',
  'ironest-xt-tab',
  'metiace-tab',
  'protilo-dm',
  'protilo-sf',
  'protilo-sf-chocolate',
  'protilo-sf-kesar',
  'protilo-chocolate',
  'protilo-kesar',
  'roxinoe-dt-tab',
  'tendofab-plus-cap',
  'tendofab-v-tab',
  'tremecya-tab',
  'tremecya-d-tab',
  'upfolet-plus-tab',
  'upfolet-tab'
)
ON CONFLICT ("productId") DO NOTHING;
