-- Import baseline approved buyers from BUYERS.md for admin order placement.
-- The source file does not include email addresses, so deterministic internal
-- placeholder emails under buyers.parshlo.local are used for these admin-created
-- buyer records. Rows marked GSTIN NO receive unique UNREGISTERED-### values to
-- satisfy the existing unique GSTIN constraint.

UPDATE "Product"
SET "packaging" = '15 tablets/strip - 10 strips/box',
    "updatedAt" = NOW()
WHERE "slug" = 'ironest-xt-tab';

INSERT INTO "User" (
  "id",
  "auth0Id",
  "email",
  "fullName",
  "roles",
  "accountStatus",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'imported-buyer-001',
    'pending|buyer-001@buyers.parshlo.local',
    'buyer-001@buyers.parshlo.local',
    'AAI MEDICAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-002',
    'pending|buyer-002@buyers.parshlo.local',
    'buyer-002@buyers.parshlo.local',
    'ADITYA MEDICAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-003',
    'pending|buyer-003@buyers.parshlo.local',
    'buyer-003@buyers.parshlo.local',
    'AKANSHA MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-004',
    'pending|buyer-004@buyers.parshlo.local',
    'buyer-004@buyers.parshlo.local',
    'AL KHAIR MEDICAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-005',
    'pending|buyer-005@buyers.parshlo.local',
    'buyer-005@buyers.parshlo.local',
    'AMAN MEDICAL & GEN STORE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-006',
    'pending|buyer-006@buyers.parshlo.local',
    'buyer-006@buyers.parshlo.local',
    'AMIBICA DISTRIBUTORS',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-007',
    'pending|buyer-007@buyers.parshlo.local',
    'buyer-007@buyers.parshlo.local',
    'ANAND MEDICAL DISTRIBUTORS',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-008',
    'pending|buyer-008@buyers.parshlo.local',
    'buyer-008@buyers.parshlo.local',
    'ANAND MEDILINK PRIVATE LIMITED',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-009',
    'pending|buyer-009@buyers.parshlo.local',
    'buyer-009@buyers.parshlo.local',
    'ANURAJ MEDICALS VITA',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-010',
    'pending|buyer-010@buyers.parshlo.local',
    'buyer-010@buyers.parshlo.local',
    'ARIHANT AGENCIES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-011',
    'pending|buyer-011@buyers.parshlo.local',
    'buyer-011@buyers.parshlo.local',
    'ASHA PATIL DR',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-012',
    'pending|buyer-012@buyers.parshlo.local',
    'buyer-012@buyers.parshlo.local',
    'ASHIRWAD MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-013',
    'pending|buyer-013@buyers.parshlo.local',
    'buyer-013@buyers.parshlo.local',
    'BEWELL MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-014',
    'pending|buyer-014@buyers.parshlo.local',
    'buyer-014@buyers.parshlo.local',
    'DATTACHARYA CLINIC DR PRADNYA SAKPAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-015',
    'pending|buyer-015@buyers.parshlo.local',
    'buyer-015@buyers.parshlo.local',
    'DE NOVO HEALTHCARE CLINIC',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-016',
    'pending|buyer-016@buyers.parshlo.local',
    'buyer-016@buyers.parshlo.local',
    'DHANWANTARI CLINIC DRAVINASH PATIL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-017',
    'pending|buyer-017@buyers.parshlo.local',
    'buyer-017@buyers.parshlo.local',
    'DNYANASHREE MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-018',
    'pending|buyer-018@buyers.parshlo.local',
    'buyer-018@buyers.parshlo.local',
    'DR SARODE CLINIC',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-019',
    'pending|buyer-019@buyers.parshlo.local',
    'buyer-019@buyers.parshlo.local',
    'DR GUGALE''S HAPPY JOINTS CLINIC',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-020',
    'pending|buyer-020@buyers.parshlo.local',
    'buyer-020@buyers.parshlo.local',
    'DSILVA & DSILVA',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-021',
    'pending|buyer-021@buyers.parshlo.local',
    'buyer-021@buyers.parshlo.local',
    'GIRIDHARLAL AGENCY',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-022',
    'pending|buyer-022@buyers.parshlo.local',
    'buyer-022@buyers.parshlo.local',
    'GLOBAL HEALTHCARE (PARTNERSHIP)',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-023',
    'pending|buyer-023@buyers.parshlo.local',
    'buyer-023@buyers.parshlo.local',
    'GUPTA MEDICAL & GEN STORE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-024',
    'pending|buyer-024@buyers.parshlo.local',
    'buyer-024@buyers.parshlo.local',
    'GURUKRUPA HEALTH CARE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-025',
    'pending|buyer-025@buyers.parshlo.local',
    'buyer-025@buyers.parshlo.local',
    'JAYASHRI CLINIC DR ASHWINI CHOPADE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-026',
    'pending|buyer-026@buyers.parshlo.local',
    'buyer-026@buyers.parshlo.local',
    'JAYDEEP MEDICAL AND GENERAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-027',
    'pending|buyer-027@buyers.parshlo.local',
    'buyer-027@buyers.parshlo.local',
    'KAJAVE DENTAL CLINIC OR PARAG KAIVE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-028',
    'pending|buyer-028@buyers.parshlo.local',
    'buyer-028@buyers.parshlo.local',
    'KONKAN DISTRIBUTORS',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-029',
    'pending|buyer-029@buyers.parshlo.local',
    'buyer-029@buyers.parshlo.local',
    'KRUSHNA MEDICAL & GEN STORE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-030',
    'pending|buyer-030@buyers.parshlo.local',
    'buyer-030@buyers.parshlo.local',
    'KRUSHNAKANT MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-031',
    'pending|buyer-031@buyers.parshlo.local',
    'buyer-031@buyers.parshlo.local',
    'KULKARNI CLINIC & HOMED CARE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-032',
    'pending|buyer-032@buyers.parshlo.local',
    'buyer-032@buyers.parshlo.local',
    'MANE NURSING HOME DIR SONALI MANE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-033',
    'pending|buyer-033@buyers.parshlo.local',
    'buyer-033@buyers.parshlo.local',
    'MANGAL SAI MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-034',
    'pending|buyer-034@buyers.parshlo.local',
    'buyer-034@buyers.parshlo.local',
    'MATRUBAL MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-035',
    'pending|buyer-035@buyers.parshlo.local',
    'buyer-035@buyers.parshlo.local',
    'MUNDHE MEDICAL & GENERAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-036',
    'pending|buyer-036@buyers.parshlo.local',
    'buyer-036@buyers.parshlo.local',
    'NEW POLAWAR MEDICAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-037',
    'pending|buyer-037@buyers.parshlo.local',
    'buyer-037@buyers.parshlo.local',
    'NEW SUSHILADEVI MEDICAL AND GENERAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-038',
    'pending|buyer-038@buyers.parshlo.local',
    'buyer-038@buyers.parshlo.local',
    'NIRANJAN MEDICO',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-039',
    'pending|buyer-039@buyers.parshlo.local',
    'buyer-039@buyers.parshlo.local',
    'NITIN AGENCY',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-040',
    'pending|buyer-040@buyers.parshlo.local',
    'buyer-040@buyers.parshlo.local',
    'OMSA PHYSIOTHERAPY CLINIC CHIPLUN',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-041',
    'pending|buyer-041@buyers.parshlo.local',
    'buyer-041@buyers.parshlo.local',
    'ORTHOWIN SPECIALITY CLINIC DR. CHETAN OSWAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-042',
    'pending|buyer-042@buyers.parshlo.local',
    'buyer-042@buyers.parshlo.local',
    'PK MEDICALS',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-043',
    'pending|buyer-043@buyers.parshlo.local',
    'buyer-043@buyers.parshlo.local',
    'PUROHIT HOSPITAL MEDICAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-044',
    'pending|buyer-044@buyers.parshlo.local',
    'buyer-044@buyers.parshlo.local',
    'RAHUL MEDICAL AND GENERAL STORE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-045',
    'pending|buyer-045@buyers.parshlo.local',
    'buyer-045@buyers.parshlo.local',
    'SAI MEDICAL & GENERAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-046',
    'pending|buyer-046@buyers.parshlo.local',
    'buyer-046@buyers.parshlo.local',
    'SAMARTH MEDICOSE UNITZ',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-047',
    'pending|buyer-047@buyers.parshlo.local',
    'buyer-047@buyers.parshlo.local',
    'SANAP MEDICAL STORE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-048',
    'pending|buyer-048@buyers.parshlo.local',
    'buyer-048@buyers.parshlo.local',
    'SHEEN CLINICS DR. OBAID UL NISAR',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-049',
    'pending|buyer-049@buyers.parshlo.local',
    'buyer-049@buyers.parshlo.local',
    'SHIVTE/ MEDICAL & GENERAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-050',
    'pending|buyer-050@buyers.parshlo.local',
    'buyer-050@buyers.parshlo.local',
    'SHREE DATTA MEDICAL & GEN STORE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-051',
    'pending|buyer-051@buyers.parshlo.local',
    'buyer-051@buyers.parshlo.local',
    'SHREE HARIHAR MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-052',
    'pending|buyer-052@buyers.parshlo.local',
    'buyer-052@buyers.parshlo.local',
    'SHREE SAMARTH MEDICAL & GENERAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-053',
    'pending|buyer-053@buyers.parshlo.local',
    'buyer-053@buyers.parshlo.local',
    'SHREE KRISHNANAND AUSHAD DUKAN',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-054',
    'pending|buyer-054@buyers.parshlo.local',
    'buyer-054@buyers.parshlo.local',
    'SHRI CLINIC OR MANASI FOSHI',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-055',
    'pending|buyer-055@buyers.parshlo.local',
    'buyer-055@buyers.parshlo.local',
    'SHRI GANESH AGENCIES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-056',
    'pending|buyer-056@buyers.parshlo.local',
    'buyer-056@buyers.parshlo.local',
    'SHRI MAHADEV MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-057',
    'pending|buyer-057@buyers.parshlo.local',
    'buyer-057@buyers.parshlo.local',
    'SHRI MAHALAXMI MEDICAL KAVATHEMAHANKAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-058',
    'pending|buyer-058@buyers.parshlo.local',
    'buyer-058@buyers.parshlo.local',
    'SHRI MAHALAXMI MEDICALS KOLHAPUR',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-059',
    'pending|buyer-059@buyers.parshlo.local',
    'buyer-059@buyers.parshlo.local',
    'SHRI MEDICALS',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-060',
    'pending|buyer-060@buyers.parshlo.local',
    'buyer-060@buyers.parshlo.local',
    'SHRI SAMARTH MEDICAL & GENERAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-061',
    'pending|buyer-061@buyers.parshlo.local',
    'buyer-061@buyers.parshlo.local',
    'SHRI SHANTADURGA MEDICALS',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-062',
    'pending|buyer-062@buyers.parshlo.local',
    'buyer-062@buyers.parshlo.local',
    'SHRISAI ARYOGYA SEVA PVT LTD SIDOHIVINAYAK',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-063',
    'pending|buyer-063@buyers.parshlo.local',
    'buyer-063@buyers.parshlo.local',
    'SIDDHI MEDICAL & GENRAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-064',
    'pending|buyer-064@buyers.parshlo.local',
    'buyer-064@buyers.parshlo.local',
    'SNEH MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-065',
    'pending|buyer-065@buyers.parshlo.local',
    'buyer-065@buyers.parshlo.local',
    'SNOWBELL MEDICAL STORE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-066',
    'pending|buyer-066@buyers.parshlo.local',
    'buyer-066@buyers.parshlo.local',
    'SRUJAN INNOVATIVE GYNAEC CARE DA NEURGAON SUNRISE PHARMACEUTICALS DISTRIBUTORS',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-067',
    'pending|buyer-067@buyers.parshlo.local',
    'buyer-067@buyers.parshlo.local',
    'SUSHILADEVI MEDICAL & GEN STORE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-068',
    'pending|buyer-068@buyers.parshlo.local',
    'buyer-068@buyers.parshlo.local',
    'SUVIDHA MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-069',
    'pending|buyer-069@buyers.parshlo.local',
    'buyer-069@buyers.parshlo.local',
    'THE SPINEWALA CLINIC',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-070',
    'pending|buyer-070@buyers.parshlo.local',
    'buyer-070@buyers.parshlo.local',
    'TODKAR MEDICAL GENERAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-071',
    'pending|buyer-071@buyers.parshlo.local',
    'buyer-071@buyers.parshlo.local',
    'TRUPTI MEDICAL & GEN STORE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-072',
    'pending|buyer-072@buyers.parshlo.local',
    'buyer-072@buyers.parshlo.local',
    'TUSHAR MEDICAL AND DISTRIBUTORS',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-073',
    'pending|buyer-073@buyers.parshlo.local',
    'buyer-073@buyers.parshlo.local',
    'VARAD NURSING HOME MEDICAL STORE VELHAL MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-074',
    'pending|buyer-074@buyers.parshlo.local',
    'buyer-074@buyers.parshlo.local',
    'VENKATESH AGENCIES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-075',
    'pending|buyer-075@buyers.parshlo.local',
    'buyer-075@buyers.parshlo.local',
    'VENKATESH MEDICAL AND GENERAL STORE',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-076',
    'pending|buyer-076@buyers.parshlo.local',
    'buyer-076@buyers.parshlo.local',
    'VIGHNAHARTA AGENCIES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-077',
    'pending|buyer-077@buyers.parshlo.local',
    'buyer-077@buyers.parshlo.local',
    'YASHODA MEDICAL',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-078',
    'pending|buyer-078@buyers.parshlo.local',
    'buyer-078@buyers.parshlo.local',
    'YOGESHWARI MEDICAL STORES',
    ARRAY['BUYER']::"Role"[],
    'APPROVED'::"AccountStatus",
    NOW(),
    NOW()
  )
ON CONFLICT ("id") DO UPDATE SET
  "auth0Id" = EXCLUDED."auth0Id",
  "email" = EXCLUDED."email",
  "fullName" = EXCLUDED."fullName",
  "roles" = EXCLUDED."roles",
  "accountStatus" = EXCLUDED."accountStatus",
  "deletedAt" = NULL,
  "updatedAt" = NOW();

INSERT INTO "BusinessProfile" (
  "id",
  "userId",
  "businessName",
  "businessType",
  "gstin",
  "pan",
  "drugLicenseNumber",
  "pharmacyRegistrationNumber",
  "mobile",
  "businessEmail",
  "addressLine1",
  "addressLine2",
  "city",
  "state",
  "pin",
  "country",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'imported-buyer-profile-001',
    'imported-buyer-001',
    'AAI MEDICAL STORES',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-001',
    NULL,
    '20-60812821-608129',
    NULL,
    '9766261100',
    'buyer-001@buyers.parshlo.local',
    'AAI MEDICAL STORES',
    NULL,
    'PARBHANI',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-002',
    'imported-buyer-002',
    'ADITYA MEDICAL STORES',
    'PHARMACY'::"BusinessType",
    '27ABFFA0833P129',
    NULL,
    'RAT/20/142162, RAT/21/142163, RAT/20C/142164',
    NULL,
    '7410525399',
    'buyer-002@buyers.parshlo.local',
    'ADITYA MEDICAL STORES',
    NULL,
    'CHIPLUN',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-003',
    'imported-buyer-003',
    'AKANSHA MEDICAL',
    'PHARMACY'::"BusinessType",
    '27AXYPH5343L1Z0',
    NULL,
    '20-MH-LAT-555903, 21-MH-LAT-555904',
    NULL,
    '9049445421',
    'buyer-003@buyers.parshlo.local',
    'AKANSHA MEDICAL',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-004',
    'imported-buyer-004',
    'AL KHAIR MEDICAL STORES',
    'PHARMACY'::"BusinessType",
    '27KEYP56914F12)',
    NULL,
    '20-487098, 21-487099',
    NULL,
    '9822769688',
    'buyer-004@buyers.parshlo.local',
    'AL KHAIR MEDICAL STORES',
    NULL,
    'CH SAMBHAJI NAGAR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-005',
    'imported-buyer-005',
    'AMAN MEDICAL & GEN STORE',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-005',
    NULL,
    '20-362985, 21-362986',
    NULL,
    '7020624030',
    'buyer-005@buyers.parshlo.local',
    'AMAN MEDICAL & GEN STORE',
    NULL,
    'PARLI VALJNATH',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-006',
    'imported-buyer-006',
    'AMIBICA DISTRIBUTORS',
    'DISTRIBUTOR'::"BusinessType",
    '27AANPD2343N12)',
    NULL,
    '208414555, 218414556',
    NULL,
    '9860613345',
    'buyer-006@buyers.parshlo.local',
    'AMIBICA DISTRIBUTORS',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-007',
    'imported-buyer-007',
    'ANAND MEDICAL DISTRIBUTORS',
    'DISTRIBUTOR'::"BusinessType",
    '27AAZPR81780125',
    NULL,
    '208279160, 216279162',
    NULL,
    '9890002088',
    'buyer-007@buyers.parshlo.local',
    'ANAND MEDICAL DISTRIBUTORS',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-008',
    'imported-buyer-008',
    'ANAND MEDILINK PRIVATE LIMITED',
    'PHARMACY'::"BusinessType",
    '27ABDCA3427C1Z4',
    NULL,
    'MH-P21-610352, MH-P21-610353',
    NULL,
    '9890002088',
    'buyer-008@buyers.parshlo.local',
    'ANAND MEDILINK PRIVATE LIMITED',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-009',
    'imported-buyer-009',
    'ANURAJ MEDICALS VITA',
    'PHARMACY'::"BusinessType",
    '27AVUPP6168P129',
    NULL,
    'SNG-20-298264, SNG-21-298265',
    NULL,
    '9860282390',
    'buyer-009@buyers.parshlo.local',
    'ANURAJ MEDICALS VITA',
    NULL,
    'VITA',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-010',
    'imported-buyer-010',
    'ARIHANT AGENCIES',
    'DISTRIBUTOR'::"BusinessType",
    '2780KPK1814D1Z7',
    NULL,
    '208-79326200-79328, 218-79327',
    NULL,
    '7972314157',
    'buyer-010@buyers.parshlo.local',
    'ARIHANT AGENCIES',
    NULL,
    'SATARA',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-011',
    'imported-buyer-011',
    'ASHA PATIL DR',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-011',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9049950602',
    'buyer-011@buyers.parshlo.local',
    'ASHA PATIL DR',
    NULL,
    'KAVATHEMAHANKAL',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-012',
    'imported-buyer-012',
    'ASHIRWAD MEDICAL',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-012',
    NULL,
    'K20-532927,K21-532928',
    NULL,
    '8275268047',
    'buyer-012@buyers.parshlo.local',
    'ASHIRWAD MEDICAL',
    NULL,
    'KOLHAPUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-013',
    'imported-buyer-013',
    'BEWELL MEDICAL',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-013',
    NULL,
    '20MH-RAT-501419,21MH-RAT-501420',
    NULL,
    '7219478780',
    'buyer-013@buyers.parshlo.local',
    'BEWELL MEDICAL',
    NULL,
    'DAPOL',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-014',
    'imported-buyer-014',
    'DATTACHARYA CLINIC DR PRADNYA SAKPAL',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-014',
    NULL,
    'NOT PROVIDED',
    NULL,
    '8378828099',
    'buyer-014@buyers.parshlo.local',
    'DATTACHARYA CLINIC DR PRADNYA SAKPAL',
    NULL,
    '147889 A / PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-015',
    'imported-buyer-015',
    'DE NOVO HEALTHCARE CLINIC',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-015',
    NULL,
    'NOT PROVIDED',
    NULL,
    '7249796395',
    'buyer-015@buyers.parshlo.local',
    'DE NOVO HEALTHCARE CLINIC',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-016',
    'imported-buyer-016',
    'DHANWANTARI CLINIC DRAVINASH PATIL',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-016',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9527590657',
    'buyer-016@buyers.parshlo.local',
    'DHANWANTARI CLINIC DRAVINASH PATIL',
    NULL,
    'CHIPLUN',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-017',
    'imported-buyer-017',
    'DNYANASHREE MEDICAL',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-017',
    NULL,
    'MH-PZS-574252, MH-P25-574253',
    NULL,
    '9607871819',
    'buyer-017@buyers.parshlo.local',
    'DNYANASHREE MEDICAL',
    NULL,
    'PCMC',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-018',
    'imported-buyer-018',
    'DR SARODE CLINIC',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-018',
    NULL,
    'MMC-2007-05-1517',
    NULL,
    '9766304876',
    'buyer-018@buyers.parshlo.local',
    'DR SARODE CLINIC',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-019',
    'imported-buyer-019',
    'DR GUGALE''S HAPPY JOINTS CLINIC',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-019',
    NULL,
    'MMC-2007-05-1517',
    NULL,
    '9766304876',
    'buyer-019@buyers.parshlo.local',
    'DR GUGALE''S HAPPY JOINTS CLINIC',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-020',
    'imported-buyer-020',
    'DSILVA & DSILVA',
    'PHARMACY'::"BusinessType",
    '30ABSP00558P1ZF',
    NULL,
    '208-7115-218-7116',
    NULL,
    '7820832361',
    'buyer-020@buyers.parshlo.local',
    'DSILVA & DSILVA',
    NULL,
    'UNKNOWN',
    'GA',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-021',
    'imported-buyer-021',
    'GIRIDHARLAL AGENCY',
    'DISTRIBUTOR'::"BusinessType",
    '27AABFG0897N1ZX',
    NULL,
    '0-499954,208-300836,21-499955,218-300838',
    NULL,
    '9822517499',
    'buyer-021@buyers.parshlo.local',
    'GIRIDHARLAL AGENCY',
    NULL,
    'PCMC',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-022',
    'imported-buyer-022',
    'GLOBAL HEALTHCARE (PARTNERSHIP)',
    'PHARMACY'::"BusinessType",
    '27AAEFG20890121',
    NULL,
    '208-154256, 218-154257',
    NULL,
    '9860207961',
    'buyer-022@buyers.parshlo.local',
    'GLOBAL HEALTHCARE (PARTNERSHIP)',
    NULL,
    'NARAYANGAON',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-023',
    'imported-buyer-023',
    'GUPTA MEDICAL & GEN STORE',
    'PHARMACY'::"BusinessType",
    '27ABAPG2084M12M',
    NULL,
    'RTN20-244254,RTN21-244256,RTN20C-244255',
    NULL,
    '9273704414',
    'buyer-023@buyers.parshlo.local',
    'GUPTA MEDICAL & GEN STORE',
    NULL,
    'CHIPLUN / SHIRGAON',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-024',
    'imported-buyer-024',
    'GURUKRUPA HEALTH CARE',
    'PHARMACY'::"BusinessType",
    '27588P563540125',
    NULL,
    '20-595755,21-595756',
    NULL,
    '9371015090',
    'buyer-024@buyers.parshlo.local',
    'GURUKRUPA HEALTH CARE',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-025',
    'imported-buyer-025',
    'JAYASHRI CLINIC DR ASHWINI CHOPADE',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-025',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9359180176',
    'buyer-025@buyers.parshlo.local',
    'JAYASHRI CLINIC DR ASHWINI CHOPADE',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-026',
    'imported-buyer-026',
    'JAYDEEP MEDICAL AND GENERAL STORES',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-026',
    NULL,
    '20-351548,21-351550',
    NULL,
    '7775884010',
    'buyer-026@buyers.parshlo.local',
    'JAYDEEP MEDICAL AND GENERAL STORES',
    NULL,
    'SATARA',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-027',
    'imported-buyer-027',
    'KAJAVE DENTAL CLINIC OR PARAG KAIVE',
    'HOSPITAL'::"BusinessType",
    '27NOKAJAVEDENTA',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9665046139',
    'buyer-027@buyers.parshlo.local',
    'KAJAVE DENTAL CLINIC OR PARAG KAIVE',
    NULL,
    'ICHALKARANII',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-028',
    'imported-buyer-028',
    'KONKAN DISTRIBUTORS',
    'DISTRIBUTOR'::"BusinessType",
    '27ABDPG673381ZW',
    NULL,
    '208364758,206364759,218364760',
    NULL,
    '9422434554',
    'buyer-028@buyers.parshlo.local',
    'KONKAN DISTRIBUTORS',
    NULL,
    'KANKAVLI',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-029',
    'imported-buyer-029',
    'KRUSHNA MEDICAL & GEN STORE',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-029',
    NULL,
    '20/284348,21/284349',
    NULL,
    '9028840098',
    'buyer-029@buyers.parshlo.local',
    'KRUSHNA MEDICAL & GEN STORE',
    NULL,
    'NASHIK',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-030',
    'imported-buyer-030',
    'KRUSHNAKANT MEDICAL',
    'PHARMACY'::"BusinessType",
    '278FOP52359AIZA',
    NULL,
    'MH-SAT-20-574900,21-574901,200-574902',
    NULL,
    '8408033852',
    'buyer-030@buyers.parshlo.local',
    'KRUSHNAKANT MEDICAL',
    NULL,
    'LONAND',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-031',
    'imported-buyer-031',
    'KULKARNI CLINIC & HOMED CARE',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-031',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9970309888',
    'buyer-031@buyers.parshlo.local',
    'KULKARNI CLINIC & HOMED CARE',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-032',
    'imported-buyer-032',
    'MANE NURSING HOME DIR SONALI MANE',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-032',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9371270425',
    'buyer-032@buyers.parshlo.local',
    'MANE NURSING HOME DIR SONALI MANE',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-033',
    'imported-buyer-033',
    'MANGAL SAI MEDICAL',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-033',
    NULL,
    'MH-P22-566378',
    NULL,
    '7378509067',
    'buyer-033@buyers.parshlo.local',
    'MANGAL SAI MEDICAL',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-034',
    'imported-buyer-034',
    'MATRUBAL MEDICAL',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-034',
    NULL,
    'K20/151286,21/8151287,200/151288',
    NULL,
    '9923102910',
    'buyer-034@buyers.parshlo.local',
    'MATRUBAL MEDICAL',
    NULL,
    'KOLHAPUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-035',
    'imported-buyer-035',
    'MUNDHE MEDICAL & GENERAL STORES',
    'PHARMACY'::"BusinessType",
    '27ABIPM05860170',
    NULL,
    '20-20MH-LAT-367797-200-36779821-367800',
    NULL,
    '9403100222',
    'buyer-035@buyers.parshlo.local',
    'MUNDHE MEDICAL & GENERAL STORES',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-036',
    'imported-buyer-036',
    'NEW POLAWAR MEDICAL STORES',
    'PHARMACY'::"BusinessType",
    '278IQPP25811171',
    NULL,
    '20-121194,21-121195',
    NULL,
    '9960280860',
    'buyer-036@buyers.parshlo.local',
    'NEW POLAWAR MEDICAL STORES',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-037',
    'imported-buyer-037',
    'NEW SUSHILADEVI MEDICAL AND GENERAL STORES',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-037',
    NULL,
    '20-604957,21-604958',
    NULL,
    '9881874200',
    'buyer-037@buyers.parshlo.local',
    'NEW SUSHILADEVI MEDICAL AND GENERAL STORES',
    NULL,
    'NILANGA',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-038',
    'imported-buyer-038',
    'NIRANJAN MEDICO',
    'PHARMACY'::"BusinessType",
    '27AISPP4396F121',
    NULL,
    'SNG-20/1037,SNG-21/1037,200/737',
    NULL,
    '7709363898',
    'buyer-038@buyers.parshlo.local',
    'NIRANJAN MEDICO',
    NULL,
    'MIRAJ',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-039',
    'imported-buyer-039',
    'NITIN AGENCY',
    'DISTRIBUTOR'::"BusinessType",
    '27AACFIN3926C1ZK',
    NULL,
    '208362838, 218362840',
    NULL,
    '9373322752',
    'buyer-039@buyers.parshlo.local',
    'NITIN AGENCY',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-040',
    'imported-buyer-040',
    'OMSA PHYSIOTHERAPY CLINIC CHIPLUN',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-040',
    NULL,
    'NOT PROVIDED',
    NULL,
    '7019680298',
    'buyer-040@buyers.parshlo.local',
    'OMSA PHYSIOTHERAPY CLINIC CHIPLUN',
    NULL,
    'CHIPLUN',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-041',
    'imported-buyer-041',
    'ORTHOWIN SPECIALITY CLINIC DR. CHETAN OSWAL',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-041',
    NULL,
    '2008/04/1608',
    NULL,
    '9769300058',
    'buyer-041@buyers.parshlo.local',
    'ORTHOWIN SPECIALITY CLINIC DR. CHETAN OSWAL',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-042',
    'imported-buyer-042',
    'PK MEDICALS',
    'PHARMACY'::"BusinessType",
    '27GNCPK8521F1ZY',
    NULL,
    '208-446936:218-446937',
    NULL,
    '9890636897',
    'buyer-042@buyers.parshlo.local',
    'PK MEDICALS',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-043',
    'imported-buyer-043',
    'PUROHIT HOSPITAL MEDICAL STORES',
    'HOSPITAL'::"BusinessType",
    '27AAZFP9741QLZT',
    NULL,
    '20-415215,21-415216200-415217-MH-PZ',
    NULL,
    '7769852895',
    'buyer-043@buyers.parshlo.local',
    'PUROHIT HOSPITAL MEDICAL STORES',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-044',
    'imported-buyer-044',
    'RAHUL MEDICAL AND GENERAL STORE',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-044',
    NULL,
    '20-241319,21-241321,200-241320',
    NULL,
    '9552509798',
    'buyer-044@buyers.parshlo.local',
    'RAHUL MEDICAL AND GENERAL STORE',
    NULL,
    'PHALTAN',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-045',
    'imported-buyer-045',
    'SAI MEDICAL & GENERAL STORES',
    'PHARMACY'::"BusinessType",
    '278YNPK5B5BGZZT',
    NULL,
    'MH-SAN-82092',
    NULL,
    '9325882558',
    'buyer-045@buyers.parshlo.local',
    'SAI MEDICAL & GENERAL STORES',
    NULL,
    'SANGALI',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-046',
    'imported-buyer-046',
    'SAMARTH MEDICOSE UNITZ',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-046',
    NULL,
    '20-553860,21-553861',
    NULL,
    '9975050202',
    'buyer-046@buyers.parshlo.local',
    'SAMARTH MEDICOSE UNITZ',
    NULL,
    'PARBHANI',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-047',
    'imported-buyer-047',
    'SANAP MEDICAL STORE',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-047',
    NULL,
    '20-216985,21-216986',
    NULL,
    '7378918885',
    'buyer-047@buyers.parshlo.local',
    'SANAP MEDICAL STORE',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-048',
    'imported-buyer-048',
    'SHEEN CLINICS DR. OBAID UL NISAR',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-048',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9082727069',
    'buyer-048@buyers.parshlo.local',
    'SHEEN CLINICS DR. OBAID UL NISAR',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-049',
    'imported-buyer-049',
    'SHIVTE/ MEDICAL & GENERAL STORES',
    'PHARMACY'::"BusinessType",
    '27ALSP071410226',
    NULL,
    '20-46219',
    NULL,
    '9130269688',
    'buyer-049@buyers.parshlo.local',
    'SHIVTE/ MEDICAL & GENERAL STORES',
    NULL,
    'AHMEDNAGAR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-050',
    'imported-buyer-050',
    'SHREE DATTA MEDICAL & GEN STORE',
    'PHARMACY'::"BusinessType",
    '27CGLP678866121',
    NULL,
    '20-MH-P23-282247,21-MH-PZ3-282248',
    NULL,
    '9172028624',
    'buyer-050@buyers.parshlo.local',
    'SHREE DATTA MEDICAL & GEN STORE',
    NULL,
    'PCMC',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-051',
    'imported-buyer-051',
    'SHREE HARIHAR MEDICAL',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-051',
    NULL,
    '20-595228 21-595229',
    NULL,
    '9423368494',
    'buyer-051@buyers.parshlo.local',
    'SHREE HARIHAR MEDICAL',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-052',
    'imported-buyer-052',
    'SHREE SAMARTH MEDICAL & GENERAL STORES',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-052',
    NULL,
    '20-4601A,21-4601A 20-C4592A',
    NULL,
    '7387882346',
    'buyer-052@buyers.parshlo.local',
    'SHREE SAMARTH MEDICAL & GENERAL STORES',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-053',
    'imported-buyer-053',
    'SHREE KRISHNANAND AUSHAD DUKAN',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-053',
    NULL,
    '20/313387,21/313388/208/313389,218/313390',
    NULL,
    '9860962300',
    'buyer-053@buyers.parshlo.local',
    'SHREE KRISHNANAND AUSHAD DUKAN',
    NULL,
    'KOLHAPLIR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-054',
    'imported-buyer-054',
    'SHRI CLINIC OR MANASI FOSHI',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-054',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9860471929',
    'buyer-054@buyers.parshlo.local',
    'SHRI CLINIC OR MANASI FOSHI',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-055',
    'imported-buyer-055',
    'SHRI GANESH AGENCIES',
    'DISTRIBUTOR'::"BusinessType",
    '271WWP50082N1ZD',
    NULL,
    '208/478547,218/478548',
    NULL,
    '9860920103',
    'buyer-055@buyers.parshlo.local',
    'SHRI GANESH AGENCIES',
    NULL,
    'PARABHANI',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-056',
    'imported-buyer-056',
    'SHRI MAHADEV MEDICAL',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-056',
    NULL,
    'K20/294053,K21/294055, K200/294054',
    NULL,
    '9975310111',
    'buyer-056@buyers.parshlo.local',
    'SHRI MAHADEV MEDICAL',
    NULL,
    'KOLHAPUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-057',
    'imported-buyer-057',
    'SHRI MAHALAXMI MEDICAL KAVATHEMAHANKAL',
    'PHARMACY'::"BusinessType",
    '278NWPP4641N120',
    NULL,
    'MH-SAN-20/114517,MH-SAN-21/114518,200/114519',
    NULL,
    '9823760068',
    'buyer-057@buyers.parshlo.local',
    'SHRI MAHALAXMI MEDICAL KAVATHEMAHANKAL',
    NULL,
    'KAVATHEMAHANKAL',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-058',
    'imported-buyer-058',
    'SHRI MAHALAXMI MEDICALS KOLHAPUR',
    'PHARMACY'::"BusinessType",
    '27ANLPM0381Q1ZC',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9422620018',
    'buyer-058@buyers.parshlo.local',
    'SHRI MAHALAXMI MEDICALS KOLHAPUR',
    NULL,
    'KOLHAPUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-059',
    'imported-buyer-059',
    'SHRI MEDICALS',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-059',
    NULL,
    '20-2747332 21-274733',
    NULL,
    '9922854429',
    'buyer-059@buyers.parshlo.local',
    'SHRI MEDICALS',
    NULL,
    'CHIPLUN',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-060',
    'imported-buyer-060',
    'SHRI SAMARTH MEDICAL & GENERAL STORES',
    'PHARMACY'::"BusinessType",
    '27AHLPC0295P1ZW',
    NULL,
    '20-3119-21-4119-200-527',
    NULL,
    '9403500452',
    'buyer-060@buyers.parshlo.local',
    'SHRI SAMARTH MEDICAL & GENERAL STORES',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-061',
    'imported-buyer-061',
    'SHRI SHANTADURGA MEDICALS',
    'PHARMACY'::"BusinessType",
    '27AENP17474E224',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9657717651',
    'buyer-061@buyers.parshlo.local',
    'SHRI SHANTADURGA MEDICALS',
    NULL,
    'KOLHAPUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-062',
    'imported-buyer-062',
    'SHRISAI ARYOGYA SEVA PVT LTD SIDOHIVINAYAK',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-062',
    NULL,
    '20-129779-21-129780',
    NULL,
    '9623440387',
    'buyer-062@buyers.parshlo.local',
    'SHRISAI ARYOGYA SEVA PVT LTD SIDOHIVINAYAK',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-063',
    'imported-buyer-063',
    'SIDDHI MEDICAL & GENRAL',
    'PHARMACY'::"BusinessType",
    '27AOVPK68448121',
    NULL,
    '20MH-F24-40778, 200-40780, 21-40779',
    NULL,
    '9422000142',
    'buyer-063@buyers.parshlo.local',
    'SIDDHI MEDICAL & GENRAL',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-064',
    'imported-buyer-064',
    'SNEH MEDICAL',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-064',
    NULL,
    'MH-20-KOL-334662,MH-21-KOL-334663',
    NULL,
    '9545512218',
    'buyer-064@buyers.parshlo.local',
    'SNEH MEDICAL',
    NULL,
    'KOLHAPUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-065',
    'imported-buyer-065',
    'SNOWBELL MEDICAL STORE',
    'PHARMACY'::"BusinessType",
    '27ACGF55277D1ZX',
    NULL,
    '20MHP23-83816,21MHPZ3-83817',
    NULL,
    '9850933512',
    'buyer-065@buyers.parshlo.local',
    'SNOWBELL MEDICAL STORE',
    NULL,
    'PCMC',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-066',
    'imported-buyer-066',
    'SRUJAN INNOVATIVE GYNAEC CARE DA NEURGAON SUNRISE PHARMACEUTICALS DISTRIBUTORS',
    'DISTRIBUTOR'::"BusinessType",
    '27A15P63709Q1Z)',
    NULL,
    '208415063,200415064,210415065',
    NULL,
    '9822053723',
    'buyer-066@buyers.parshlo.local',
    'SRUJAN INNOVATIVE GYNAEC CARE DA NEURGAON SUNRISE PHARMACEUTICALS DISTRIBUTORS',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-067',
    'imported-buyer-067',
    'SUSHILADEVI MEDICAL & GEN STORE',
    'PHARMACY'::"BusinessType",
    'UNREGISTERED-067',
    NULL,
    '20-4989321-49894',
    NULL,
    '9881874200',
    'buyer-067@buyers.parshlo.local',
    'SUSHILADEVI MEDICAL & GEN STORE',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-068',
    'imported-buyer-068',
    'SUVIDHA MEDICAL',
    'PHARMACY'::"BusinessType",
    '27ALIPC66140120',
    NULL,
    '20-MH-SAT-332668,21-MH-SAT-332669',
    NULL,
    '9405309128',
    'buyer-068@buyers.parshlo.local',
    'SUVIDHA MEDICAL',
    NULL,
    'PHALTAN',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-069',
    'imported-buyer-069',
    'THE SPINEWALA CLINIC',
    'HOSPITAL'::"BusinessType",
    'UNREGISTERED-069',
    NULL,
    'NOT PROVIDED',
    NULL,
    '9404313832',
    'buyer-069@buyers.parshlo.local',
    'THE SPINEWALA CLINIC',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-070',
    'imported-buyer-070',
    'TODKAR MEDICAL GENERAL STORES',
    'PHARMACY'::"BusinessType",
    '27AHQPT1988F1Z1',
    NULL,
    '20-341648,21-341649',
    NULL,
    '9370037792',
    'buyer-070@buyers.parshlo.local',
    'TODKAR MEDICAL GENERAL STORES',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-071',
    'imported-buyer-071',
    'TRUPTI MEDICAL & GEN STORE',
    'PHARMACY'::"BusinessType",
    '27ABNPK3686/171',
    NULL,
    '20/369072/200/369073/21/369074',
    NULL,
    '9404153836',
    'buyer-071@buyers.parshlo.local',
    'TRUPTI MEDICAL & GEN STORE',
    NULL,
    'CHIPLUN',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-072',
    'imported-buyer-072',
    'TUSHAR MEDICAL AND DISTRIBUTORS',
    'DISTRIBUTOR'::"BusinessType",
    '27GFLP54864A1ZY',
    NULL,
    '208-394003,218394004',
    NULL,
    '9421306002',
    'buyer-072@buyers.parshlo.local',
    'TUSHAR MEDICAL AND DISTRIBUTORS',
    NULL,
    'UDGIR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-073',
    'imported-buyer-073',
    'VARAD NURSING HOME MEDICAL STORE VELHAL MEDICAL',
    'HOSPITAL'::"BusinessType",
    '27AAVFV40070121',
    NULL,
    '20-472116,21-472117, 20-418560,20C-418562,21-418561',
    NULL,
    '7769852895',
    'buyer-073@buyers.parshlo.local',
    'VARAD NURSING HOME MEDICAL STORE VELHAL MEDICAL',
    NULL,
    'PUNE',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-074',
    'imported-buyer-074',
    'VENKATESH AGENCIES',
    'DISTRIBUTOR'::"BusinessType",
    '27CDXPM80398121',
    NULL,
    '208-BEE-91462,218-BEE-91463',
    NULL,
    '9921852038',
    'buyer-074@buyers.parshlo.local',
    'VENKATESH AGENCIES',
    NULL,
    'BEED',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-075',
    'imported-buyer-075',
    'VENKATESH MEDICAL AND GENERAL STORE',
    'PHARMACY'::"BusinessType",
    '278TYPD14096121',
    NULL,
    '20-MH-5A7-474669,21-MH-SAT-474670',
    NULL,
    '9766563704',
    'buyer-075@buyers.parshlo.local',
    'VENKATESH MEDICAL AND GENERAL STORE',
    NULL,
    'PHALTAN',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-076',
    'imported-buyer-076',
    'VIGHNAHARTA AGENCIES',
    'DISTRIBUTOR'::"BusinessType",
    '27CQHPC66246127',
    NULL,
    'NOT PROVIDED',
    NULL,
    '8208148172',
    'buyer-076@buyers.parshlo.local',
    'VIGHNAHARTA AGENCIES',
    NULL,
    'BEED',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-077',
    'imported-buyer-077',
    'YASHODA MEDICAL',
    'PHARMACY'::"BusinessType",
    '27CNPPB7273L1ZE',
    NULL,
    '20-565500,200-565502,21-565501',
    NULL,
    '7755942828',
    'buyer-077@buyers.parshlo.local',
    'YASHODA MEDICAL',
    NULL,
    'ICHALKARANJI',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  ),
  (
    'imported-buyer-profile-078',
    'imported-buyer-078',
    'YOGESHWARI MEDICAL STORES',
    'PHARMACY'::"BusinessType",
    '27CCFPB80421121',
    NULL,
    '20-213612, 21-213613,200213614',
    NULL,
    '8208394952',
    'buyer-078@buyers.parshlo.local',
    'YOGESHWARI MEDICAL STORES',
    NULL,
    'LATUR',
    'MH',
    '000000',
    'IN',
    NOW(),
    NOW()
  )
ON CONFLICT ("userId") DO UPDATE SET
  "businessName" = EXCLUDED."businessName",
  "businessType" = EXCLUDED."businessType",
  "gstin" = EXCLUDED."gstin",
  "pan" = EXCLUDED."pan",
  "drugLicenseNumber" = EXCLUDED."drugLicenseNumber",
  "pharmacyRegistrationNumber" = EXCLUDED."pharmacyRegistrationNumber",
  "mobile" = EXCLUDED."mobile",
  "businessEmail" = EXCLUDED."businessEmail",
  "addressLine1" = EXCLUDED."addressLine1",
  "addressLine2" = EXCLUDED."addressLine2",
  "city" = EXCLUDED."city",
  "state" = EXCLUDED."state",
  "pin" = EXCLUDED."pin",
  "country" = EXCLUDED."country",
  "updatedAt" = NOW();

INSERT INTO "KycApplication" (
  "id",
  "userId",
  "status",
  "submittedAt",
  "reviewedAt",
  "reviewerNote"
)
VALUES
  (
    'imported-buyer-kyc-001',
    'imported-buyer-001',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-002',
    'imported-buyer-002',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-003',
    'imported-buyer-003',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-004',
    'imported-buyer-004',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-005',
    'imported-buyer-005',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-006',
    'imported-buyer-006',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-007',
    'imported-buyer-007',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-008',
    'imported-buyer-008',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-009',
    'imported-buyer-009',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-010',
    'imported-buyer-010',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-011',
    'imported-buyer-011',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-012',
    'imported-buyer-012',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-013',
    'imported-buyer-013',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-014',
    'imported-buyer-014',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-015',
    'imported-buyer-015',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-016',
    'imported-buyer-016',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-017',
    'imported-buyer-017',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-018',
    'imported-buyer-018',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-019',
    'imported-buyer-019',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-020',
    'imported-buyer-020',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-021',
    'imported-buyer-021',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-022',
    'imported-buyer-022',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-023',
    'imported-buyer-023',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-024',
    'imported-buyer-024',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-025',
    'imported-buyer-025',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-026',
    'imported-buyer-026',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-027',
    'imported-buyer-027',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-028',
    'imported-buyer-028',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-029',
    'imported-buyer-029',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-030',
    'imported-buyer-030',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-031',
    'imported-buyer-031',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-032',
    'imported-buyer-032',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-033',
    'imported-buyer-033',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-034',
    'imported-buyer-034',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-035',
    'imported-buyer-035',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-036',
    'imported-buyer-036',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-037',
    'imported-buyer-037',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-038',
    'imported-buyer-038',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-039',
    'imported-buyer-039',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-040',
    'imported-buyer-040',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-041',
    'imported-buyer-041',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-042',
    'imported-buyer-042',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-043',
    'imported-buyer-043',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-044',
    'imported-buyer-044',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-045',
    'imported-buyer-045',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-046',
    'imported-buyer-046',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-047',
    'imported-buyer-047',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-048',
    'imported-buyer-048',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-049',
    'imported-buyer-049',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-050',
    'imported-buyer-050',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-051',
    'imported-buyer-051',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-052',
    'imported-buyer-052',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-053',
    'imported-buyer-053',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-054',
    'imported-buyer-054',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-055',
    'imported-buyer-055',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-056',
    'imported-buyer-056',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-057',
    'imported-buyer-057',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-058',
    'imported-buyer-058',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-059',
    'imported-buyer-059',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-060',
    'imported-buyer-060',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-061',
    'imported-buyer-061',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-062',
    'imported-buyer-062',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-063',
    'imported-buyer-063',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-064',
    'imported-buyer-064',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-065',
    'imported-buyer-065',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-066',
    'imported-buyer-066',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-067',
    'imported-buyer-067',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-068',
    'imported-buyer-068',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-069',
    'imported-buyer-069',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-070',
    'imported-buyer-070',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-071',
    'imported-buyer-071',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-072',
    'imported-buyer-072',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-073',
    'imported-buyer-073',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-074',
    'imported-buyer-074',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-075',
    'imported-buyer-075',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-076',
    'imported-buyer-076',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-077',
    'imported-buyer-077',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  ),
  (
    'imported-buyer-kyc-078',
    'imported-buyer-078',
    'APPROVED'::"KycStatus",
    NOW(),
    NOW(),
    'Imported from baseline buyer list.'
  )
ON CONFLICT ("id") DO UPDATE SET
  "status" = EXCLUDED."status",
  "reviewedAt" = EXCLUDED."reviewedAt",
  "reviewerNote" = EXCLUDED."reviewerNote";
